name: Emma
command_prefix: '-'
locale: en
talents:
  - examples
  - wonderful
  - gestalt
  - i18n
  - configure
  - paintjob
  - reminder
  - twitchnotify
  - minigames
  - coinflip
  - eightball
  - cleverbot
clients:
  - discord
  - twitch
directory: /Users/kserebour/Personal/Lavenza-II/app/bots/emma
